PRAGMA foreign_keys = ON;
BEGIN;
INSERT INTO defined_term_set(id,type,name,identifier) VALUES ('ontology','DefinedTermSet','Example ontology','https://example.org/ontology');
INSERT INTO defined_term(id,type,name,tan,identifier,in_defined_term_set_id) VALUES ('term','DefinedTerm','Published','EX:1','https://example.org/term','ontology');
INSERT INTO defined_term(id,type,name,in_defined_term_set_url) VALUES ('url-term','DefinedTerm','Equipment','https://example.org/ontology');
INSERT INTO organization(id,type,name,url) VALUES ('org','Organization','Research institute','https://example.org');
INSERT INTO agent(id,type,name,given_name,family_name) VALUES ('agent','Agent','Ada Example','Ada','Example');
INSERT INTO agent_email VALUES ('agent',0,'ada@example.org');
INSERT INTO agent_identifier VALUES ('agent',0,'researcher-1');
INSERT INTO agent_affiliation VALUES ('agent',0,'org');
INSERT INTO agent_job_title VALUES ('agent',0,'term');
INSERT INTO scholarly_article(id,type,headline,creative_work_status_id) VALUES ('article','ScholarlyArticle','Example study','term');
INSERT INTO scholarly_article_author VALUES ('article',0,'agent');
INSERT INTO scholarly_article_identifier VALUES ('article',0,'doi:example');
INSERT INTO dataset(id,type,title,license,date_created) VALUES ('root','Dataset','Combined example','CC-BY-4.0','2026-01-01');
INSERT INTO dataset(id,type) VALUES ('provenance','Dataset'),('semantic','Dataset'),('admin','Dataset');
INSERT INTO dataset_identifier VALUES ('root',0,'arc-example'),('root',1,'arc-example'),('provenance',0,'processes'),('semantic',0,'descriptions'),('admin',0,'metadata');
INSERT INTO dataset_conforms_to VALUES ('root',0,'administrative'),('root',1,'process-provenance'),('root',2,'semantic-designation'),('provenance',0,'process-provenance'),('semantic',0,'semantic-designation'),('admin',0,'administrative');
INSERT INTO dataset_has_part VALUES ('root',0,'provenance'),('root',1,'semantic'),('root',2,'admin'),('root',3,'semantic');
INSERT INTO dataset_has_part VALUES ('admin',0,'provenance');
INSERT INTO sample(id,type,name) VALUES ('source','Sample','Source'),('sample','Sample','Prepared sample');
INSERT INTO data(id,type,path,encoding_format) VALUES ('file','Data','results.csv','text/csv'),('same-file','Data','results.csv','text/csv');
INSERT INTO data(id,type,path,selector,selector_format) VALUES ('fragment','Data','results.csv','col=2','https://www.rfc-editor.org/rfc/rfc7111');
INSERT INTO data_has_part VALUES ('file',0,'fragment');
INSERT INTO dataset_data_file VALUES ('root',0,'file'),('root',1,'same-file');
INSERT INTO annotation(id,type,name,value_number,unit,instance_of_id) VALUES ('temperature','Annotation','Temperature',22.5,'Celsius','parameter');
INSERT INTO annotation(id,type,name,value_text) VALUES ('text','Annotation','Text value','42'),('component','Annotation','Equipment','Instrument');
INSERT INTO annotation(id,type,name,value_number) VALUES ('number','Annotation','Numeric value',42.0),('zero','Annotation','Zero',0.0);
INSERT INTO annotation(id,type,name) VALUES ('absent','Annotation','Absent value');
INSERT INTO annotation(id,type,name,value_text) VALUES ('empty','Annotation','Empty text','');
INSERT INTO formal_parameter(id,type,name,default_value_id) VALUES ('parameter','FormalParameter','Temperature','temperature');
INSERT INTO recipe(id,type,name,intended_use_id) VALUES ('recipe','Recipe','Preparation','term');
INSERT INTO recipe(id,type,intended_use_text) VALUES ('text-recipe','Recipe','term');
INSERT INTO recipe_parameter VALUES ('recipe',0,'parameter');
INSERT INTO recipe_component VALUES ('recipe',0,'component');
INSERT INTO recipe_additional_property VALUES ('recipe',0,'text');
INSERT INTO process(id,type,name,executes_recipe_id) VALUES ('prepare','Process','Preparation','recipe'),('measure','Process','Measurement','text-recipe');
INSERT INTO process_io VALUES ('prepare','input','source',NULL),('prepare','output','sample',NULL),('measure','input','sample',NULL),('measure','output',NULL,'file');
INSERT INTO dataset_process VALUES ('provenance',0,'prepare'),('provenance',1,'measure'),('root',0,'prepare');
INSERT INTO process_parameter_value VALUES ('prepare',0,'temperature'),('prepare',1,'temperature');
INSERT INTO descriptor(id,type,sample_id) VALUES ('sample-description','Descriptor','sample');
INSERT INTO descriptor(id,type,data_id) VALUES ('file-description','Descriptor','file');
INSERT INTO descriptor_annotation VALUES ('sample-description',0,'text'),('sample-description',1,'number'),('sample-description',2,'text'),('file-description',0,'zero');
INSERT INTO dataset_descriptor VALUES ('semantic',0,'sample-description'),('semantic',1,'file-description');
INSERT INTO dataset_agent VALUES ('root',0,'agent');
INSERT INTO dataset_citation VALUES ('root',0,'article');
INSERT INTO dataset_additional_property VALUES ('root',0,'text');
INSERT INTO sample_additional_property VALUES ('sample',0,'text');
INSERT INTO data_additional_property VALUES ('file',0,'text');
INSERT INTO agent_additional_property VALUES ('agent',0,'text');
INSERT INTO scholarly_article_additional_property VALUES ('article',0,'text');
INSERT INTO dataset_additional_type VALUES ('root',0,'example'),('root',1,'example');
COMMIT;
