import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdirSync, existsSync } from "node:fs";
import { ARC, Session } from "arc-session";
import { Dataset, Sample } from "arc-base-model";

const folder = `build/out/arc-session/native-js-${randomUUID()}`;
mkdirSync(folder, { recursive: true });
const path = `${folder}/collection.sqlite`;
const root = () => {
  const value = new Dataset(["process-provenance"], ["native"]);
  value.Id = "root";
  return value;
};
let session = Session.createFile(path);
const first = session.createArc(root());
const second = session.createArc(root());
const sample = new Sample("first");
sample.Id = "same";
first.Sample.upsert(sample);
const other = new Sample("second");
other.Id = "same";
second.Sample.upsert(other);
const process = first.Process.create("process");
assert.throws(() => first.Process.setInputSample(process, other));
first.Process.setInputSample(process, sample);
first.Dataset.addProcess(first.Model, process);
first.Sample.setName(sample, "changed");
first.History.undo();
assert.equal(sample.Name, "first");
assert.equal(second.Sample.get("same").Name, "second");
assert.equal(session.openArc(first.ArcId), first);
assert.equal(session.listArcs().length, 2);
first.bindFolder(`${folder}/export`);
assert.equal(existsSync(`${folder}/export/arc.yml`), false);
first.save();
const firstId = first.ArcId;
const secondId = second.ArcId;
first.close();
assert.throws(() => first.Sample.create("closed"));
second.Sample.setName(other, "independent");
session.close();
session = Session.openFile(path);
const resumed = session.openArc(firstId);
assert.equal(resumed.Model.Processes[0].Input, resumed.Sample.get("same"));
resumed.History.redo();
assert.equal(resumed.Sample.get("same").Name, "changed");
assert.equal(session.openArc(secondId).Sample.get("same").Name, "independent");
assert.throws(() => Session.createFile(path));
const memory = Session.createInMemory();
const imported = ARC.importFolder(memory, `${folder}/export`);
assert.equal(imported.Model.Processes[0].Input.Name, "first");
memory.close();
session.close();
assert.throws(() => resumed.save());
console.log("Native JavaScript ARC session checks passed.");
